### ISSUE TITLE
Production Release

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/Site_Expense#1]
@dhirendra-isgec The Site Expense Module is to be released on production by DevOps.

**Comment by dhirendra-isgec** [comment]
action done

**Comment by hariharan-isgec** [comment]
@dhirendra-isgec Issues related to first time installation fixed, QC testing done. You may re-sync the repository for re-installation

**Comment by dhirendra-isgec** [comment]
Re-sync done

**Comment by dhirendra-isgec** [comment]
Re-sync done
