### ISSUE TITLE
Error While Running in Production 

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/Site_Expense#3]
![image](https://user-images.githubusercontent.com/43699418/61975024-9b662b00-b005-11e9-8bce-21996644ed71.png)
The Technical Name of the module in Production is Site_Expense.
Whereas the PDF Report is calling
![image](https://user-images.githubusercontent.com/43699418/61975149-fc8dfe80-b005-11e9-916b-bd946c735425.png)
@dhirendra-isgec @RajeevKumarmbd Need to validate the consistency of Repository name

**Comment by hariharan-isgec** [comment]
1. PAN Number should be mandatory only if TDS is entered

**Comment by hariharan-isgec** [comment]
2. Verification field should not be editable for Site Employee

**Comment by hariharan-isgec** [comment]
3. PAN NUMBER size validation required

**Comment by hariharan-isgec** [comment]
4. All date filed should have validation that it cannot be future date and Wherever date range is taken as input, From Date <= To Date

**Comment by hariharan-isgec** [comment]
5. In Expense Statement (A) TOTAL should be of Final Amount

**Comment by hariharan-isgec** [comment]
6. In Expense Data for HO session , The field label has '(', which is to be removed

(VERIFIED TOTAL
--

**Comment by RajeevKumarmbd** [comment]
5. In Expense Statement (A) TOTAL should be of Final Amount
    Total of Final Amount Done

**Comment by RajeevKumarmbd** [comment]
1. In Expense Data for HO session , The field label has '(', which is to be removed
The field label has '(', which is to be removed
Needful Done

**Comment by RajeevKumarmbd** [comment]
Date Formate Setting  In   (DD/MM/YYY)
In Odoo   Setting --> Translations -->Languages

**Comment by RajeevKumarmbd** [comment]
1 . PAN Number should be mandatory only if TDS is entered
puts "Colorize me".fg(111).bg(226).underline

**Comment by RajeevKumarmbd** [comment]
1. PAN Number should be mandatory only if TDS is entered
 3 .PAN NUMBER size validation required

Both Point Are Complete

**Comment by RajeevKumarmbd** [comment]
1. Verification field should not be editable for Site Employee
Needful Done

**Comment by RajeevKumarmbd** [comment]
Problem of Pan No. Solve
You can save record Without Pan No  With Pan No
if You  enter TDS ,  Then  Pan No. will be fill Proper way
